LIBNAME ANALYSIS 'H:\NKOMO';

PROC TTEST DATA = ANALYSIS.DATA ALPHA = 0.05;
PAIRED MACROSCOPIC_PRE*MACROSCOPIC_POST;
RUN;

PROC TTEST DATA = ANALYSIS.DATA ALPHA = 0.05;
PAIRED MICROSCOPIC_PRE*MICROSCOPIC_POST;
RUN;

PROC TTEST DATA = ANALYSIS.DATA ALPHA = 0.05;
PAIRED SYMBOLIC_PRE*SYMBOLIC_POST;
RUN;

PROC TTEST DATA = ANALYSIS.DATA ALPHA = 0.05;
PAIRED SYNTHESIS_PRE*SYNTHESIS_POST;
RUN;

*THE RELATIONSHIP CAN BE EXAMINED IN EITHER DIRECTION. REPLICATING THE ANALYIS WITH POST - PRE WILL SIMULATE A SIMILAR DISTRIBUTION. ;

PROC TTEST DATA = ANALYSIS.DATA ALPHA = 0.05;
PAIRED MACROSCOPIC_POST*MACROSCOPIC_PRE;
RUN;

PROC TTEST DATA = ANALYSIS.DATA ALPHA = 0.05;
PAIRED MICROSCOPIC_POST*MICROSCOPIC_PRE;
RUN;

PROC TTEST DATA = ANALYSIS.DATA ALPHA = 0.05;
PAIRED SYMBOLIC_POST*SYMBOLIC_PRE;
RUN;

PROC TTEST DATA = ANALYSIS.DATA ALPHA = 0.05;
PAIRED SYNTHESIS_POST*SYNTHESIS_PRE;
RUN;
